
production:
  adapter: postgresql
  database: buckets_production
  username: rails
  password: PYsUZ6reRH
  host: localhost
  port: 5432

development:
  adapter: postgresql
  database: buckets_dev
  username: rails
  password: PYsUZ6reRH
  host: localhost
  port: 5432

